config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  resources :tweets, only: [:index, :create, :destroy]
  resources :users, only: [:edit, :update]
  resources :follows, only: [:index, :create, :destroy]
  resources :favorites, only: :update
  get '/auth/twitter/callback', to: 'sessions#create'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  has_many :followers_tweets, as: :ownerable, dependent: :delete_all, class_name: 'Tweet'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :account
  belongs_to :ownerable, polymorphic: true

  scope :latest, -> { order(created_at: :desc) }
  scope :favorites, -> { where(favorite: true).latest }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :account, dependent: :destroy
  has_many :followers, dependent: :destroy
  has_many :followers_tweets, through: :followers
  has_many :tweets, as: :ownerable, dependent: :delete_all

  mount_uploader :image, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_current_user

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  private

  def require_current_user
    redirect_to root_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :current_tweet

  def update
    favorite_value = params[:favorite].to_i
    @tweet.update(favorite: favorite_value)
    manage_favorite(favorite_value, @tweet.tweet_id)
    flash[:notice] = flash_message(favorite_value)
  end

  private

  def flash_message(value)
    value.zero? ? 'Successfully unfavorited' : 'Successfully favorited'
  end

  def twitter_client
    @client ||= TwitterClient.new(current_user.account)
  end

  def current_tweet
    @tweet = Tweet.find(params[:id])
  end

  def manage_favorite(value, id)
    value.zero? ? twitter_client.unfavorite(id) : twitter_client.favorite(id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index
    @followers = current_user.followers
    @tweets = current_user.followers_tweets.latest
  end

  def create
    follower = twitter_client.follow(params[:nickname]).first
    follower = current_user.followers.create(name: follower.name, twitter_user_id: follower.id)
    load_followers_tweets(follower)
    redirect_to follows_path, notice: 'Successfully followed.'
  end

  private

  def load_followers_tweets(follower)
    twitter_client.tweets(follower.twitter_user_id).each do |tweet|
      follower.followers_tweets.create(tweet_id: tweet.id, text: tweet.text)
    end
  end

  def twitter_client
    @client ||= TwitterClient.new(current_user.account)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_current_user, only: :create

  def create
    if account
      user
    else
      create_user
      FetchTwitterData.new(user, account)
    end
    session[:user_id] = user.id
    redirect_to tweets_path, notice: 'Welcome!'
  end

  private

  def user
    account.user
  end

  def account
    Account.find_by(provider: request_params[:provider], uid: request_params[:uid])
  end

  def create_user
    User.create(user_attrs).create_account(account_attrs)
  end

  def request_params
    request.env['omniauth.auth']
  end

  def user_attrs
    params_info = request_params[:info]
    {
      nickname: params_info[:nickname],
      name: params_info[:name],
      remote_image_url: params_info[:image]
    }
  end

  def account_attrs
    params_credentials = request_params[:credentials]
    {
      token: params_credentials[:token],
      secret: params_credentials[:secret],
      provider: request_params[:provider],
      uid: request_params[:uid]
    }
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  skip_before_action :require_current_user, only: :index

  def index
    @tweet = Tweet.new
  end

  def create
    new_tweet = twitter_client.tweet(tweet_params[:text])
    @tweet = current_user.tweets.create(tweet_params.merge(tweet_id: new_tweet.id))
    flash.now[:notice] = 'Tweet was successfully created.'
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    twitter_client.destroy(@tweet.tweet_id)
    @tweet.destroy
    flash.now[:notice] = 'Tweet was successfully deleted.'
  end

  private

  def tweet_params
    params.require(:tweet).permit(:text)
  end

  def twitter_client
    TwitterClient.new(current_user.account)
  end

  def own_tweets
    current_user.tweets.latest
  end
  helper_method :own_tweets

  def favorites_tweets
    current_user.tweets.favorites.latest
  end
  helper_method :favorites_tweets
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user

  def edit
  end

  def update
    current_user.update(user_params)
    update_user_data
    flash.now[:notice] = 'Successfully updated '
  end

  private

  def update_user_data
    twitter_client.update_name(current_user.name) if user_params[:name].present?
    twitter_client.update_profile_image(image_file) if user_params[:image].present?
  end

  def image_file
    File.open(current_user.image.file.file)
  end

  def user_params
    params.require(:user).permit(:name, :image)
  end

  def require_user
    redirect_to root_path unless current_user && current_user.id.to_s == params[:id]
  end

  def twitter_client
    @client ||= TwitterClient.new(current_user.account)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follows/_form.html.slim
.row
  = form_tag :follows, id: 'new_follow', remote: true do
    .form-group.col-md-6
      = text_field_tag :nickname, nil, class: 'form-control', placeholder: 'Follow someone'
    .col-md-1
      = submit_tag 'Follow someone', class: 'btn btn-success'

app/views/follows/_tweet.html.slim
tr id = tweet.id
  td = tweet.text
  td = tweet.ownerable.name
  - if tweet.favorite
    td = link_to 'Unfavorite', favorite_path(tweet, favorite: 0), remote: true, method: :patch
  - else
    td = link_to 'Favorite', favorite_path(tweet, favorite: 1), remote: true, method: :patch

app/views/follows/_tweets.html.slim
h3 Followers tweets
table.table
  tr
    th Text
    th Username
    th
  - tweets.each do |tweet|
    = render 'tweet', tweet: tweet

app/views/follows/create.js.erb
$('.tweets').html("<%= j render 'tweets', tweets: @tweets %>");
$(".flash_messages").append("<%= j render('shared/flash_messages') %>");

app/views/follows/index.html.slim
.row
  .col-md-6
    = render 'form'
    h3 Your followers
    - @followers.each do |follower|
      p = follower.name
  .col-md-6
    .tweets
      = render 'tweets', tweets: @tweets

app/views/layouts/application.html.slim
doctype 5
html
  head
    title TwitterApp
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container-fluid
      = render 'shared/header'
      .flash_messages
        = render 'shared/flash_messages'
    .container
      = yield

app/views/replies/new.html.slim
= form_tag :replies do
  = text_field_tag :text
  = hidden_field_tag :tweet_id, params[:tweet_id]
  = submit_tag 'Add comment'

app/views/shared/_flash_messages.html.slim
- flash.each do |key, value|
  div class=("alert alert-success")
    = value

app/views/shared/_header.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Twitter app', root_path, class: 'navbar-brand'
    #navbar.navbar-collapse.collapse
      - if current_user
        ul.nav.navbar-nav
          li
            = link_to 'Followers & tweets', follows_path
        ul.nav.navbar-nav.navbar-right
          li
            = link_to current_user.nickname, edit_user_path(current_user)

app/views/tweets/_form.html.slim
.row
  = form_for @tweet, remote: true do |f|
    .form-group.col-md-3
      = f.text_field :text, class: 'form-control', placeholder: 'New tweet'
    .col-md-1
      = f.submit :submit, class: 'btn btn-success'

app/views/tweets/_tweet.html.slim
tr id = tweet.id
  td = tweet.text
  - if delete
    td = link_to 'Delete', tweet_path(tweet), remote: true, method: :delete
  - if tweet.favorite
    td = link_to 'Unfavorite', favorite_path(tweet, favorite: 0), remote: true,  method: :patch
  - else
    td = link_to 'Favorite', favorite_path(tweet, favorite: 1), remote: true, method: :patch

app/views/tweets/_tweets.html.slim
h3 = title
table.table
  tr
    th Text
    th
    th
  - tweets.each do |tweet|
    = render tweet, delete: delete

app/views/tweets/index.html.slim
- unless current_user
  = link_to 'Twitter Signin', '/auth/twitter'
- else
  = render 'form'
  .row
    .col-md-6
      .tweets
        = render 'tweets', tweets: own_tweets, title: 'Your tweets', delete: true
    .col-md-6
      = render 'tweets', tweets: favorites_tweets, title: 'Favorite tweets', delete: false

app/views/users/_form.html.slim
.col-md-2
  = image_tag current_user.image.url(:medium)
.col-md-10
  = form_for current_user, remote: true do |f|
    .form-group.col-md-3
      p
        ' Your cool name:
        = current_user.name
      = f.text_field :name, value: nil, class: 'form-control', placeholder: 'Enter new name'
    .form-group.col-md-12
      = f.file_field :image
    .form-group.col-md-12
      = f.submit class: 'btn btn-success'

app/views/users/edit.html.slim
.row
  .current_user_form
    = render 'form'